### ISSUE TITLE
vitrines

### ISSUE THREAD

**Issue by isadequech** [isadequech/tickets_mobile#10]
Comentário Daniel: parece que temos vitrine intermediaria pra poucos produtos - so vi em camisetas. Será que é boa opçao? Por exemplo, em Novos nao faria sentido ter? E outras categorias com multiplos modelos como UW?

**Comment by renatodex** [comment]
Discussão muito filosófica pra um ticket, precisamos de algo mais concreto.
Vamos conversar melhor sobre isso, e ai saímos com uma solução mais concreta.

**Comment by isadequech** [comment]
double click - evento para todas as categorias
