### ISSUE TITLE
menu: hamburguinho seleciona direto FEMININO sempre

### ISSUE THREAD

**Issue by isadequech** [isadequech/tickets_mobile#11]
Comentário Daniel: se minha ultima seleçao no menu foi de item masculino, ao clicar de novo deveriamos ter como default o ultimo genero navegado, e nao necessariamente voltar pro feminimo como default toda vez.  Precisamos ajustar. 
toda vez que abre o menu de navegaçao, ele mostra como default o menu feminino. Mas se eu estava navegando no masculino ao chamar o Menu, é provavel que esta seja a categoria mais relevante, portanto nesta chamada deveria mostrar a categoria de Masculino como selecionado. Basicamente, o menu deveria mostrar sempre a categoria da ultima navegaçao como default. Na primeira navegaçao, ok, que default seja feminino.

**Comment by renatodex** [comment]
Isso é realmente bom, mas não é tão destrutivo na navegação ter o menu de gênero não selecionado.
Como falamos, o projeto é uma adaptação da versão mobile pra versão desktop, qualquer coisa que entre além disso é melhoria de UX e que pode ser adiada para uma segunda entrega.
