### ISSUE TITLE
fluxo de compra não logado: pedir login só quando clicar em FINALIZAR COMPRA

### ISSUE THREAD

**Issue by isadequech** [isadequech/tickets_mobile#2]
Comentário Daniel: sem login, ao adicionar um item ele pede pra preencher cadastro ou logar. Ruim interromper o flow assim. Deveria ser como no desktop, ele preenche ou conecta no momento da primeira compra. Temos que rever.

**Comment by renatodex** [comment]
será feito depois do lançamento, numa segunda entrega.
