### ISSUE TITLE
página de produto: incluir ícone que indique que existem outras fotos

### ISSUE THREAD

**Issue by isadequech** [isadequech/tickets_mobile#4]
Comentário Daniel: modal fica popping up a cada pagina quase quando nao logado. Very annoying, precisamos ajustar.

**Comment by isadequech** [comment]
opa, o comentário certo é este: nao está claro que tem que swipe pra ver outras fotos do produto. Temos que incluir o icone - ver everlane.

**Comment by isadequech** [comment]
opa, o comentário certo é este: nao está claro que tem que swipe pra ver outras fotos do produto. Temos que incluir o icone - ver everlane.

**Comment by isadequech** [comment]
opa, o comentário certo é este: nao está claro que tem que swipe pra ver outras fotos do produto. Temos que incluir o icone - ver everlane.

**Comment by renatodex** [comment]
Preciso de um icone de Swipe para adicionar à página de produto.
Ainda não temos como identificar se a imagem de um produto foi carregada. Portanto, se o icone de swap ficasse sobre a imagem, ele invariavelmente ficaria em cima da imagem de loading também.

**Comment by isadequech** [comment]
precisamos de um ícone de passar foto pra página de produto do mobile :)

_isadora salomão_
marketing
(11) 991 515 188

---

https://app.getsignals.com/link?url=http%3A%2F%2Ffacebook.com%2Fbasico&ukey=agxzfnNpZ25hbHNjcnhyGAsSC1VzZXJQcm9maWxlGICAgID-6O8KDA&k=c074dcb295f14d28855cbae02b6f5680

https://app.getsignals.com/link?url=http%3A%2F%2Ftwitter.com%2Fbasicopontocom&ukey=agxzfnNpZ25hbHNjcnhyGAsSC1VzZXJQcm9maWxlGICAgID-6O8KDA&k=0d0b44037c6f4d11ad3f4b1de4b57a88

https://app.getsignals.com/link?url=http%3A%2F%2Finstagram.com%2Fsoubasico&ukey=agxzfnNpZ25hbHNjcnhyGAsSC1VzZXJQcm9maWxlGICAgID-6O8KDA&k=5e8fec2483794c5297ce6e0c47c65a81

## https://app.getsignals.com/link?url=http%3A%2F%2Fpinterest.com%2Fbasicopontocom&ukey=agxzfnNpZ25hbHNjcnhyGAsSC1VzZXJQcm9maWxlGICAgID-6O8KDA&k=90ce43245504489bb37838bf629df6d1

[image: basico.com]

## https://app.getsignals.com/link?url=http%3A%2F%2Fo.basi.co%2F19iEb5f&ukey=agxzfnNpZ25hbHNjcnhyGAsSC1VzZXJQcm9maWxlGICAgID-6O8KDA&k=0846b8945eba47e6937a4305118bfc40

11 3083-0677 | contato@basico.com
https://app.getsignals.com/link?url=mailto%3Acontato%40basico.com&ukey=agxzfnNpZ25hbHNjcnhyGAsSC1VzZXJQcm9maWxlGICAgID-6O8KDA&k=f68d0fe4589441989712c9ab055745d5

## seg a sex, das 9h as 18h

## 

Em 12 de agosto de 2015 15:01, Renato Alves notifications@github.com
escreveu:

**Comment by renatodex** [comment]
Vamos usar uma bolinha default de sliders.
